config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root "articles#index" # torna o index a pagina principal. não precisando necessáriamente dar um /article.
  
  
  # get "/articles", to: "articles#index" # rota index principal. Leva ao metodo chamado index.
  # get "/articles/:id", to: "articles#show"

  resources :articles do
    resources :comments
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  belongs_to :admin
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 6 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
  end
  

app/controllers/application_controller.rb
# class ApplicationController < ActionController::Base
#   # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
#   allow_browser versions: :modern
# end


class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Método de autorização para administradores
  private

  def authorize_admin!
    unless admin_signed_in?
      redirect_to root_path, alert: "Você não tem permissão para realizar essa ação."
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin!, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show

  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.admin_id = current_admin.id 
    if @article.save
      redirect_to @article, notice: 'Publicação registrada com sucesso.'
    else
      logger.debug "Erro ao criar artigo: #{@article.errors.full_messages}"
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Artigo atualizado com sucesso.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path, notice: 'Artigo excluído com sucesso.', status: :see_other
  end

  private

  def set_post
    @article = Article.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Artigo não encontrado."
    redirect_to articles_path
  end

  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
  def authorize_user!
    unless @article.user == current_user
      flash[:alert] = "Você não tem permissão para realizar essa ação."
      redirect_to articles_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_admin!, only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>

    <div>
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private'], selected: article.status || 'public' %>
    </div>

    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>

  
  <% end %>
  

app/views/articles/edit.html.erb
<h1>Editar Artigo</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="site-intro">
  <h2>Site de Publicações de artigos, com acervo de:</h2>
  <p><strong><%= Article.public_count %> </strong> trabalhos publicados.</p>
</div>

<ul class="produtos">
  <% if @articles.present? %>
    <% @articles.each do |article| %>
      <% unless article.archived? %>
        <li class="li-artigo">
          <h2><%= link_to article.title, article %></h2>
        </li>
      <% end %>
    <% end %>
  <% else %>
    <li>Nenhum artigo encontrado.</li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>Novo Artigo</h1>
 
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><strong>Título da Publicação: </strong><%= @article.title %></h1>

<p><strong>Descrição: </strong><%= @article.body %></p>
<p><strong>Publicado em:</strong><%= @article.created_at.strftime("%d/%m/%Y %H:%M") %></p>
<ul>
  <li><%= link_to "Editar", edit_article_path(@article) %></li>
  <% if @article.admin == current_admin %>
    <li><%= link_to "Excluir", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Você tem certeza de que deseja EXCLUIR esse artigo?"
                  } %></li>
  <% end %>
</ul>
<p><%= link_to "Voltar para a tela principal", articles_path, class: "btn btn-back" %></p>
<h2>Comentários nesta publicação: </h2>
<%= render @article.comments %>

<h2>Adicionar comentários: </h2>
<%= render "comments/form", article: @article %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Autor:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comentário:</strong>
    <%= comment.body %>
  </p>
  <p>
    <strong>Publicado em:</strong>
    <%= comment.created_at.strftime("%d/%m/%Y %H:%M") %> <!-- Exibe a data e hora do comentário -->
  </p>
  <p>
    <%= link_to "Apagar Comentário", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Vocẽ tem certeza de que deseja DELETAR esse comentário?"
                } %>

  </p>
<% end %>
<p>
  <%= link_to "Voltar para a tela principal", articles_path, class: "btn btn-back" %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ article, article.comments.build ] do |form| %>



    <p>
      <%= form.label :"Autor do comentário" %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :"Comentário" %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <input type="submit" name="commit" value="Criar cometário" data-disable-with="Create Comment">
    </p>


    <p>
      <%= form.label :status %><br>
      <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
    </p>
  <% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title><%= content_for(:title) || "Aurora Publicações" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'style', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Condicional para esconder o cabeçalho e rodapé na tela de login -->
    <% if controller_name != 'sessions' || action_name != 'new' %>
      <header>
        <div class="header-container">
          <h1>Aurora Publicações</h1>
          <p>Bem-vindo, <%= current_admin.email %>!</p>
        </div>
      </header>
    <% end %>

    <main>
      <%= yield %>
    </main>

    <% if controller_name != 'sessions' || action_name != 'new' %>
      <nav>
        <ul class="nav-links">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Criar Novo Artigo', new_article_path %></li>
          <% if admin_signed_in? %>
            <li><%= link_to 'Desconectar', destroy_admin_session_path, method: :delete, data: { turbo: false }, class: 'btn btn-logout' %></li>
          <% else %>
            <li><%= link_to 'Login', new_admin_session_path, class: 'btn btn-login' %></li>
          <% end %>
        </ul>
      </nav>
    <% end %>
    <% if controller_name != 'sessions' || action_name != 'new' %>
      <footer>
        <p class="copyright">&copy; Copyright Aurora Publicações - 2024</p>
      </footer>
    <% end %>
  </body>
</html>